"""Add tables coingecko_coindata and coingecko_cointag

Revision ID: 020d14ebe79e
Revises: 2dac1246c154
Create Date: 2020-08-30 21:36:04.322285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020d14ebe79e'
down_revision = '2dac1246c154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coingecko_coindata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_platform_id', sa.String(), nullable=True),
    sa.Column('public_notice', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('twitter_screen_name', sa.String(), nullable=True),
    sa.Column('telegram_channel_identifier', sa.String(), nullable=True),
    sa.Column('image_url_thumb', sa.String(), nullable=True),
    sa.Column('image_url_small', sa.String(), nullable=True),
    sa.Column('image_url_large', sa.String(), nullable=True),
    sa.Column('country_origin', sa.String(), nullable=True),
    sa.Column('sentiment_votes_up_percentage', sa.Numeric(), nullable=True),
    sa.Column('sentiment_votes_down_percentage', sa.Numeric(), nullable=True),
    sa.Column('market_cap_rank', sa.Numeric(), nullable=True),
    sa.Column('coingecko_rank', sa.Numeric(), nullable=True),
    sa.Column('coingecko_score', sa.Numeric(), nullable=True),
    sa.Column('developer_score', sa.Numeric(), nullable=True),
    sa.Column('community_score', sa.Numeric(), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(), nullable=True),
    sa.Column('public_interest_score', sa.Numeric(), nullable=True),
    sa.Column('twitter_followers', sa.Numeric(), nullable=True),
    sa.Column('telegram_channel_user_count', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coingecko_cointag',
    sa.Column('coin_id', sa.String(), nullable=False),
    sa.Column('tag_group_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('coin_id', 'tag_group_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coingecko_cointag')
    op.drop_table('coingecko_coindata')
    # ### end Alembic commands ###
