"""Update table coingecko_ticker

Revision ID: 2dac1246c154
Revises: c74e73d1651a
Create Date: 2020-08-30 14:47:20.641597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dac1246c154'
down_revision = 'c74e73d1651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coingecko_ticker',
    sa.Column('exchange_id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('base_coin_id', sa.String(), nullable=True),
    sa.Column('target_coin_id', sa.String(), nullable=True),
    sa.Column('last_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('converted_last_btc', sa.Numeric(), nullable=True),
    sa.Column('converted_last_eth', sa.Numeric(), nullable=True),
    sa.Column('converted_last_usd', sa.Numeric(), nullable=True),
    sa.Column('converted_volume_btc', sa.Numeric(), nullable=True),
    sa.Column('converted_volume_eth', sa.Numeric(), nullable=True),
    sa.Column('converted_volume_usd', sa.Numeric(), nullable=True),
    sa.Column('trust_score', sa.String(), nullable=True),
    sa.Column('bid_ask_spread_perc', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_traded_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('trade_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('exchange_id', 'base_currency', 'target_currency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coingecko_ticker')
    # ### end Alembic commands ###
