"""Add create coingecko_exchange

Revision ID: 3b6c4b929ec4
Revises: b89545a0d6ef
Create Date: 2020-08-29 21:08:56.539846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6c4b929ec4'
down_revision = 'b89545a0d6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
