"""Add tables coingecko_coin and coingecko_exchange

Revision ID: 3f5e25fe5e7a
Revises: 5326a89fa30e
Create Date: 2020-08-29 18:08:39.186565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5e25fe5e7a'
down_revision = '5326a89fa30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coingecko_coin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coingecko_exchange',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('has_trading_incentive', sa.Boolean(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('trust_score_rank', sa.Integer(), nullable=True),
    sa.Column('trade_volume_24h_btc', sa.Numeric(), nullable=True),
    sa.Column('trade_volume_24h_btc_normalized', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seq', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('seq', name='students_pkey')
    )
    op.drop_table('coingecko_exchange')
    op.drop_table('coingecko_coin')
    # ### end Alembic commands ###
