"""Add create/update columns for tables coingecko_coin and coingecko_exchange

Revision ID: b89545a0d6ef
Revises: 3f5e25fe5e7a
Create Date: 2020-08-29 19:15:46.146879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89545a0d6ef'
down_revision = '3f5e25fe5e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coingecko_coin', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coingecko_coin', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coingecko_exchange', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coingecko_exchange', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coingecko_exchange', 'updated_at')
    op.drop_column('coingecko_exchange', 'created_at')
    op.drop_column('coingecko_coin', 'updated_at')
    op.drop_column('coingecko_coin', 'created_at')
    # ### end Alembic commands ###
