"""Add create coingecko_exchange

Revision ID: c74e73d1651a
Revises: 3b6c4b929ec4
Create Date: 2020-08-29 21:29:23.260020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74e73d1651a'
down_revision = '3b6c4b929ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coingecko_coin', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.add_column('coingecko_exchange', sa.Column('deactivated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coingecko_exchange', 'deactivated')
    op.drop_column('coingecko_coin', 'deactivated')
    # ### end Alembic commands ###
